// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAVmfwf9c6OlHeP-XFp8SKi9jBI__SEtoo',
    appId: '1:599726188654:web:fadba9944fd5037fe31e7f',
    messagingSenderId: '599726188654',
    projectId: 'holdwise-2397a',
    authDomain: 'holdwise-2397a.firebaseapp.com',
    storageBucket: 'holdwise-2397a.firebasestorage.app',
    measurementId: 'G-RCL7GZPLLX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB1yAs2pYVnQKs7LSHuIWVaL3LfsXTQi3o',
    appId: '1:599726188654:android:b1c990cdd6fac7e9e31e7f',
    messagingSenderId: '599726188654',
    projectId: 'holdwise-2397a',
    storageBucket: 'holdwise-2397a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT53ReZwATfMHdVqg_Ak_63vEtdoRu0BE',
    appId: '1:599726188654:ios:5a88e746dad9569ce31e7f',
    messagingSenderId: '599726188654',
    projectId: 'holdwise-2397a',
    storageBucket: 'holdwise-2397a.firebasestorage.app',
    androidClientId: '599726188654-35p9778ca36f6t6a7pt2gneoi539jpea.apps.googleusercontent.com',
    iosClientId: '599726188654-mttq67emiqn16ko49tsatm6ht80e07tu.apps.googleusercontent.com',
    iosBundleId: 'com.example.holdwise',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT53ReZwATfMHdVqg_Ak_63vEtdoRu0BE',
    appId: '1:599726188654:ios:5a88e746dad9569ce31e7f',
    messagingSenderId: '599726188654',
    projectId: 'holdwise-2397a',
    storageBucket: 'holdwise-2397a.firebasestorage.app',
    androidClientId: '599726188654-35p9778ca36f6t6a7pt2gneoi539jpea.apps.googleusercontent.com',
    iosClientId: '599726188654-mttq67emiqn16ko49tsatm6ht80e07tu.apps.googleusercontent.com',
    iosBundleId: 'com.example.holdwise',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD6LmfhcCtoLAN8bcUSttAfQnmk5mj5ojs',
    appId: '1:599726188654:web:6430868e9cc20229e31e7f',
    messagingSenderId: '599726188654',
    projectId: 'holdwise-2397a',
    authDomain: 'holdwise-2397a.firebaseapp.com',
    storageBucket: 'holdwise-2397a.firebasestorage.app',
    measurementId: 'G-GHEKK8FTED',
  );
}
